In [2]:
import numpy as np
import pandas as pd
import copy

In [16]:
#question 1
#2x1+3x2+11x3=2
#x1+x2+5x3=1
#2x1+x2+3x3=0
#solution:x1=-1/3,x2=-1/3,x3=1/3

In [3]:
#question 2
def elimination(mat_a):
    for i in range(0, (mat_a.shape[0])-1):
        if mat_a[i, i] == 0:
            print("stop calculation：")
            print(mat_a)
            break
        else:
            for j in range(i+1, mat_a.shape[0]):
                mat_a[j:j+1 , :] = mat_a[j:j+1,:] - (mat_a[j,i]/mat_a[i,i])*mat_a[i, :]
    return mat_a

def back_substitute(new_mat):
    x = np.mat(np.zeros(new_mat.shape[0], dtype=float))#initial zero matrix to save answer
    number = x.shape[1]-1
    b = number+1
    x[0,number] = new_mat[number,b]/new_mat[number, number]
    for i in range(number-1,-1,-1):
        try:
            x[0,i] = (new_mat[i,b]-np.sum(np.multiply(new_mat[i,i+1:b],x[0,i+1:b])))/(new_mat[i,i])
        except:print("error")
    print(x)

if __name__ == "__main__":
    A = np.mat([[2, 3, 11],
                [1, 1, 5],
                [2, 1, 3],],dtype=float)
    b = np.mat([2,1,0])
    # conbine A and b
    print("augmented matrix")
    print(np.hstack((A, b.T)))
    new_mat = elimination(np.hstack((A, b.T)))
    print("Upper Triangular Matrix")
    print(new_mat)
    print("solution")
    back_substitute(new_mat)

augmented matrix
[[ 2.  3. 11.  2.]
 [ 1.  1.  5.  1.]
 [ 2.  1.  3.  0.]]
Upper Triangular Matrix
[[ 2.   3.  11.   2. ]
 [ 0.  -0.5 -0.5  0. ]
 [ 0.   0.  -6.  -2. ]]
solution
[[-0.33333333 -0.33333333  0.33333333]]


In [18]:
# question2 another test equation
if __name__ == "__main__":
    A = np.mat([[11, 3, 10],
                [1, 1, 5],
                [2, 1, 3],],dtype=float)
    b = np.mat([2,1,5])
    # conbine A and b
    print("augmented matrix")
    print(np.hstack((A, b.T)))
    new_mat = elimination(np.hstack((A, b.T)))
    print("Upper Triangular Matrix")
    print(new_mat)
    print("solution")
    back_substitute(new_mat)

augmented matrix
[[11.  3. 10.  2.]
 [ 1.  1.  5.  1.]
 [ 2.  1.  3.  5.]]
Upper Triangular Matrix
[[11.          3.         10.          2.        ]
 [ 0.          0.72727273  4.09090909  0.81818182]
 [ 0.          0.         -1.375       4.125     ]]
solution
[[-2. 18. -3.]]


In [19]:
# question 3
A = np.array([[1,2,3],[3,4,5]])
AT = A.transpose()
print(np.dot(A,AT))
print(np.dot(AT,A))

#if A is a m×n matrix, then AAT is a m×m matrix, while ATA is a n×n matrix.
#they are not the same in general.
#when A is a squared matrix, and it is symmetric, antisymmetric or orthogonal,
#AAT = ATA is true.

[[14 26]
 [26 50]]
[[10 14 18]
 [14 20 26]
 [18 26 34]]


In [20]:
#question 4
np.random.seed(2)
def LU_decomposition(A):
    n=len(A[0])
    L = np.zeros([n,n])
    U = np.zeros([n, n])
    for i in range(n):
        L[i][i]=1
        if i==0:
            U[0][0] = A[0][0]
            for j in range(1,n):
                U[0][j]=A[0][j]
                L[j][0]=A[j][0]/U[0][0]
        else:
                for j in range(i, n):#U
                    temp=0
                    for k in range(0, i):
                        temp = temp+L[i][k] * U[k][j]
                    U[i][j]=A[i][j]-temp
                for j in range(i+1, n):#L
                    temp = 0
                    for k in range(0, i ):
                        temp = temp + L[j][k] * U[k][i]
                    L[j][i] = (A[j][i] - temp)/U[i][i]
    return L,U
 
if __name__ == '__main__': 
    A=[[2,-1,1],[4,1,-1],[1,1,1]]
    L,U=LU_decomposition(A)
    print('L=\n',L)
    print('U=\n',U)

L=
 [[1.  0.  0. ]
 [2.  1.  0. ]
 [0.5 0.5 1. ]]
U=
 [[ 2. -1.  1.]
 [ 0.  3. -3.]
 [ 0.  0.  2.]]


In [21]:
# question 5

def permutations(n):
    arr = [x for x in range(n)]
    result =[]
    dfs(arr,0,len(arr),result)
    return result

def dfs(arr, begin, end,result):
    if begin == end:
        result.append(copy.deepcopy(arr))
        pass
    else:
        for i in range(begin,end):
            arr[i],arr[begin] = arr[begin],arr[i]
            dfs(arr,begin+1,end,result)
            arr[i],arr[begin] = arr[begin],arr[i]
            pass
        pass

def inverse(arr):
    count = 0
    for i in range(len(arr)):
        for j in range(i):
            if arr[j] > arr[i]:
                count+=1
                pass
            pass
        pass    
    return count

#determinant
def det(matrix):
    if matrix.shape[0]!=matrix.shape[1]:
        print('this martix is not a squared matrix！')
        return
    permutation = permutations(matrix.shape[0])
    permutation = np.array(permutation)
    result = 0
    for i in range(len(permutation)):
        a = 1
        for j in range(matrix.shape[0]):
            a*=matrix[j][permutation[i][j]]
        result += pow(-1,inverse(permutation[i]))*a
    return result

A1 = np.array([[2,1],[1,2]])
A2 = np.array([[2,1,1],[1,2,1],[1,1,2]])
A3 = np.array([[2,1,1,1],[1,2,1,1],[1,1,2,1],[1,1,1,2]])
print(det(A1))
print(det(A2))
print(det(A3))

3
4
5


In [22]:
# question 6
def cramer(d,b):
    if d.shape[0]!=d.shape[1]:
        print('this martix is not a squared matrix！')
        return
    if det(d) == 0:
        print('coefficient matrix is zero')
        return
    d_i = []
    for i in range(b.shape[0]):
        d_i.append(copy.deepcopy(d))
        d_i[i][:,i] = b
        pass
    x = []
    for i in range(b.shape[0]):
        x.append(det(d_i[i]) / det(d))
    print(x)

A1 = np.array([[2,1],[1,2]])
x1 = np.array([15,16])
A2 = np.array([[2,1,1],[1,2,1],[1,1,2]])
x2 = np.array([15,16,17])
A3 = np.array([[2,1,1,1],[1,2,1,1],[1,1,2,1],[1,1,1,2]])
x3 = np.array([15,16,17,18])
cramer(A1,x1)
cramer(A2,x2)
cramer(A3,x3)

[4.666666666666667, 5.666666666666667]
[3.0, 4.0, 5.0]
[1.8, 2.8, 3.8, 4.8]
