### Q1

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
# use np.intersect1d to get the intersection of two array
np.intersect1d(a, b)

array([2, 4])

### Q2

In [3]:
# generate all needed integers
a_list = [i for i in range(1, 16)]
# reshape the list and transpose the array
np.array(a_list).reshape((3, 5)).T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

### Q3

In [4]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
result = []
for i in np.intersect1d(a, b):
    # put each target number's index in a into result
    result.extend(np.where(a == i)[0].tolist())
# use np.delete to delete the target items in a
np.delete(a, result)


array([ 7, 15,  1,  8])

### Q4

In [5]:
# The aaproach is firstly inserting the original miles record into the array and using np.diff method 
# to calculate the difference between two items which is the riding miles each day.


# function get_each_day_riding is to print each day's riding miles
# starting_mile: the starting mile record of odometer
# miles_record: the cumulative mile record list

def get_each_day_riding(starting_mile, miles_record):
    # add the statring_mile to the miles_record for the first item
    # in the list
    miles_record.insert(0, starting_mile)
    # use np.diff to calculate each day's riding mile
    each_day_record = np.diff(miles_record)
    day = 1
    for i in each_day_record:
        if i == 0:
            print("Day " + str(day) + ": no riding" )
        # print each day's roading miles
        else:
            print("Day "+ str(day) + ": " + str(i) + " miles")
        day += 1

# assumption of record
odometer_record = [50, 50, 100, 150, 200, 200, 251, 305, 305, 360,
                  415, 467, 520, 565, 615, 670, 725, 780, 835, 890,
                  943, 1000, 1055, 1109, 1164, 1210, 1267, 1320, 1374,
                  1428, 1480, 1530, 1580, 1635, 1690]
get_each_day_riding(50, odometer_record)

Day 1: no riding
Day 2: no riding
Day 3: 50 miles
Day 4: 50 miles
Day 5: 50 miles
Day 6: no riding
Day 7: 51 miles
Day 8: 54 miles
Day 9: no riding
Day 10: 55 miles
Day 11: 55 miles
Day 12: 52 miles
Day 13: 53 miles
Day 14: 45 miles
Day 15: 50 miles
Day 16: 55 miles
Day 17: 55 miles
Day 18: 55 miles
Day 19: 55 miles
Day 20: 55 miles
Day 21: 53 miles
Day 22: 57 miles
Day 23: 55 miles
Day 24: 54 miles
Day 25: 55 miles
Day 26: 46 miles
Day 27: 57 miles
Day 28: 53 miles
Day 29: 54 miles
Day 30: 54 miles
Day 31: 52 miles
Day 32: 50 miles
Day 33: 50 miles
Day 34: 55 miles
Day 35: 55 miles


### Q5

In [6]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)

C:\Users\Dustin\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


numpy.ndarray

What is the maximum yearly NYC consumption of water in millions of gallons per day?

In [7]:
# get maximum value of the third column
nyc_water.max(0)[-2]

1512.0

How many calendar years are represented within this data set? NumPy's shape command is one way to find out

In [8]:
nyc_water.shape[0]

39

What is the mean and the standard deviation of the per capita daily water consumption?

In [9]:
print("Mean of the per capita daily water consumption: ", np.mean(nyc_water[:, -1]))
print("Standard deviation of the per capita daily water consumption: ", np.std(nyc_water[:, -1]))

Mean of the per capita daily water consumption:  160.30769230769232
Standard deviation of the per capita daily water consumption:  31.51894330370624


What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array
of differences and save that to a variable called "pop_diff", then print that variable to the screen.

In [10]:
pop_diff = np.diff(nyc_water[:, 1])
pop_diff

array([-30461. ,  17602. ,  19864. ,  72119. ,  53290. ,  39540. ,
        45192. ,  23230. ,  11243. ,  -9544. ,  -8525. ,  38851. ,
        54443. ,  77222. ,  64292. ,  62582. ,  64772. ,  75631. ,
        84816. ,  89401. ,  60618. ,  16685.5,  16685.5,  16685.5,
        16685.5,  16685.5,  16685.5,  16685.5,  16685.5,  16685.5,
        16685.5, 108965. ,  77081. ,  61281. ,  49530. ,  44512. ,
        21171. ,  85025. ])